jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Build with Gradle
      run: gradle build --stacktrace
name: Build with Java 8
on:
  repository_dispatch:
    types: trigger-ga___build8.yml
